[workspace]
resolver = "3"
members = [
    "seahaven-cli",
    "seahaven-compose-file",
    "seahaven-docker",
    "seahaven-just",
    "seahaven-package",
    "seahaven-package/testdata",
    "seahaven-setup-file",
    "seahaven-setup-file/testdata",
]

[workspace.package]
authors = ["Lorenzo Delgado (LNSD) <lorenzo@edgeandnode.com>"]
license = "Apache-2.0"
repository = "https://github.com/LNSD/seahaven-project"
edition = "2024"
