[workspace]
resolver = "3"
members = [
    "seahaven-cli",
    "seahaven-docker",
    "seahaven-file",
    "testlib/file-testdata",
]

[workspace.package]
authors = ["Lorenzo Delgado (LNSD) <lorenzo@edgeandnode.com>"]
license = "Apache-2.0"
repository = "https://github.com/LNSD/seahaven-project"
edition = "2024"
