[package]
name = "seahaven-cli"
description = "Seahaven CLI"
version = "0.1.0"
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version = "1.85.0"

[[bin]]
name = "truman"
path = "src/bin/truman/main.rs"

[dependencies]
anyhow = "1.0.97"
build-info = "0.0.40"
clap = { version = "4.5", features = ["cargo", "derive"] }
dotenvy = "0.15.7"
indoc = "2.0.6"
seahaven-compose-file = { version = "0.1.0", path = "../seahaven-compose-file", features = ["serde"] }
seahaven-docker = { version = "0.1.0", path = "../seahaven-docker" }
seahaven-just = { version = "0.1.0", path = "../seahaven-just" }
seahaven-package = { version = "0.1.0", path = "../seahaven-package" }
seahaven-setup-file = { version = "0.1.0", path = "../seahaven-setup-file" }
serde = { version = "1.0.197", features = ["derive"] }
serde-envfile = { version = "0.2.0", features = ["preserve_order"], git = "https://github.com/LNSD/serde-envfile.git", rev = "7d02f71" }
serde_json = { version = "1.0.140", features = ["preserve_order"] }
serde_yaml = "0.9.34"
tempfile = "3.19.1"
thiserror = "2.0.12"
tokio = { version = "1.44", features = ["rt", "macros"] }
toml = { version = "0.8.22", features = ["preserve_order"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[build-dependencies]
build-info-build = "0.0.40"

[dev-dependencies]
toml = "0.8.22"
