[package]
name = "seahaven-cli"
description = "Seahaven CLI"
version = "0.1.0"
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version = "1.85.0"

[[bin]]
name = "truman"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.97"
build-info = "0.0.40"
clap = { version = "4.5", features = ["cargo", "derive"] }
indoc = "2.0.6"
seahaven-docker = { version = "0.1.0", path = "../seahaven-docker" }
seahaven-file = { version = "0.1.0", path = "../seahaven-file" }
seahaven-just = { version = "0.1.0", path = "../seahaven-just" }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["preserve_order"] }
tempfile = "3.19.1"
thiserror = "2.0.12"
tokio = { version = "1.44", features = ["rt", "macros"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[build-dependencies]
build-info-build = "0.0.40"
